// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skgrphghnrluxryahzwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrZ3JwaGdobnJsdXhyeWFoendmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5Mzg0MzAsImV4cCI6MjA2MDUxNDQzMH0.6Mgk19rpQnykGmWRxRAccmnyxc9cRlzbKhStxvjiL3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);